version: '0.5'
services:
  web:
    container_name: BRS
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./migrations:/usr/src/app/migrations
      - .:/usr/src/app
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    container_name: BRS_DB
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  mailpit:
    image: axllent/mailpit
    container_name: BRS_MAILPIT
    restart: always
    ports:
      - "8085:8025" # Веб-интерфейс (откроешь в браузере как http://localhost:8082)
      - "1025:1025" # SMTP-сервер для Flask

#  cadvisor:
#    image: gcr.io/cadvisor/cadvisor:v0.47.0
#    container_name: brs_cadvisor
#    privileged: true
#    devices:
#      - "/dev/kmsg:/dev/kmsg"
#    restart: unless-stopped
#    volumes:
#      - /:/rootfs:ro
#      - /var/run:/var/run:ro
#      - /sys:/sys:ro
#      - /var/lib/docker/:/var/lib/docker:ro
#      - /dev/disk/:/dev/disk:ro
#    ports:
#      - "8082:8080"
#
#  prometheus:
#    image: prom/prometheus:latest
#    container_name: brs_prometheus
#    restart: unless-stopped
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#      - prometheus_data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#    ports:
#      - "9090:9090"
#    depends_on:
#      - cadvisor
#
#  grafana:
#    image: grafana/grafana:latest
#    container_name: brs_grafana
#    restart: unless-stopped
#    ports:
#      - "3000:3000"
#    volumes:
#      - grafana_data:/var/lib/grafana
#    depends_on:
#      - prometheus
#
#volumes:
#  prometheus_data:
#  grafana_data: