services:
  web:
    container_name: BRS
    build: ./
    volumes:
      - ./migrations:/usr/src/app/migrations
      - ./app:/app
    environment:
      - FLASK_DEBUG=1
    ports:
      - "8000:5000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    container_name: BRS_DB
    image: postgres:14.5
    restart: always
    environment:
      PGUSER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 5s
      retries: 10

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080