version: '3.8'

services:
  web:
    command: gunicorn --bind 0.0.0.0:5000 "app:create_app()"
    environment:
      - FLASK_DEBUG=0
      - FLASK_CONFIG=production
      - GUNICORN_CMD_ARGS=""
    volumes: !reset []
    ports: !reset []

  db:
    healthcheck:
      interval: 10s
      retries: 5

  adminer:
    ports: !reset []

  mailpit:
    ports: !reset []

  nginx:
    image: nginx:alpine
    container_name: BRS_NGINX
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      web:
        condition: service_started