server {
    listen 80;
    listen [::]:80;

    # Укажите здесь IP вашего VPS или домен (например, ://yourdomain.com)
    server_name _;

    # Максимальный размер загружаемых файлов (например, картинок от Swift-аппки)
    client_max_body_size 20M;

    location / {
        # web — это имя сервиса Flask из docker-compose.yml
        proxy_pass http://web:5000;

        # Передаем реальные заголовки, чтобы Flask понимал, откуда пришли запросы
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Важно для Swift приложения, если используются постоянные соединения (Keep-Alive)
        proxy_connect_timeout 90s;
        proxy_read_timeout 90s;
    }
}