"""empty message

Revision ID: 05a77467c5f8
Revises: 4bbe00870959
Create Date: 2026-06-06 17:47:18.426908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a77467c5f8'
down_revision = '4bbe00870959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_constraint('bars_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bars_admin_id_fkey', 'managers', ['admin_id'], ['manager_id'])

    # ### end Alembic commands ###
