"""empty message

Revision ID: 06ad0c8e02bd
Revises: 9e339d4abc0b
Create Date: 2026-09-23 18:02:12.155553

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06ad0c8e02bd'
down_revision = '9e339d4abc0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_column('opening_hours')

    # ### end Alembic commands ###
