"""drop_roles_table_and_add_string_role

Revision ID: 0b62a40bf721
Revises: 60c4c77dd86e
Create Date: 2026-09-04 21:28:50.997745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b62a40bf721'
down_revision = '60c4c77dd86e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index('ix_roles_default')

    op.drop_table('roles')
    op.drop_table('managers')
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_constraint('bars_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_constraint('drinks_bar_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bars', ['bar_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=32), nullable=False))
        batch_op.drop_constraint('users_role_id_fkey', type_='foreignkey')
        batch_op.drop_column('type')
        batch_op.drop_column('role_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_role_id_fkey', 'roles', ['role_id'], ['id'])
        batch_op.drop_column('role')

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drinks_bar_id_fkey', 'bars', ['bar_id'], ['id'])

    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bars_admin_id_fkey', 'users', ['admin_id'], ['id'])

    op.create_table('managers',
    sa.Column('manager_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='managers_manager_id_fkey'),
    sa.PrimaryKeyConstraint('manager_id', name='managers_pkey')
    )
    op.create_table('roles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('default', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('permissions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='roles_pkey'),
    sa.UniqueConstraint('name', name='roles_name_key')
    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index('ix_roles_default', ['default'], unique=False)

    # ### end Alembic commands ###
