"""empty message

Revision ID: 13adc661da70
Revises: 607fe6242148
Create Date: 2026-06-03 20:48:35.286853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13adc661da70'
down_revision = '607fe6242148'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
