"""empty message

Revision ID: 17733af2c12a
Revises: 06ad0c8e02bd
Create Date: 2026-09-28 19:59:06.767000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17733af2c12a'
down_revision = '06ad0c8e02bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_checkins', schema=None) as batch_op:
        batch_op.drop_constraint('bar_checkins_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bar_checkins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bar_checkins_user_id_fkey', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
