"""empty message

Revision ID: 36530f50bab2
Revises: 73202224e0da
Create Date: 2026-06-15 21:09:21.308530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36530f50bab2'
down_revision = '73202224e0da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_column('rating')

    # ### end Alembic commands ###
