"""empty message

Revision ID: 607fe6242148
Revises: a9c2e1325d97
Create Date: 2025-11-18 22:10:37.860760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '607fe6242148'
down_revision = 'a9c2e1325d97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
