"""empty message

Revision ID: 641ba59efad9
Revises: 05a77467c5f8
Create Date: 2026-06-09 19:38:35.019854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '641ba59efad9'
down_revision = '05a77467c5f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drink_ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'drink_id', name='_user_drink_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drink_ratings')
    # ### end Alembic commands ###
