"""empty message

Revision ID: 6532430f172a
Revises: 0e254c78ef8c
Create Date: 2025-09-21 16:34:00.405610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6532430f172a'
down_revision = '0e254c78ef8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'managers', ['admin_id'], ['manager_id'])

    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['manager_id'], ['id'])
        batch_op.drop_column('bar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('managers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bar', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
