"""empty message

Revision ID: 7835f1b64bb5
Revises: d9453ae300ef
Create Date: 2025-11-17 18:23:19.894864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7835f1b64bb5'
down_revision = 'd9453ae300ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Numeric(precision=5, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
