"""empty message

Revision ID: 8795de5f9e70
Revises: 1ecdd88fdb89
Create Date: 2026-06-23 20:40:27.606443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8795de5f9e70'
down_revision = '1ecdd88fdb89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drunk_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('drink_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drunk_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drunk_actions_timestamp'), ['timestamp'], unique=False)

    op.drop_table('drunk_drinks')
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('abv', sa.Numeric(precision=4, scale=1), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_column('abv')
        batch_op.drop_column('volume')

    op.create_table('drunk_drinks',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drink_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name='drunk_drinks_drink_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='drunk_drinks_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'drink_id', name='drunk_drinks_pkey')
    )
    with op.batch_alter_table('drunk_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drunk_actions_timestamp'))

    op.drop_table('drunk_actions')
    # ### end Alembic commands ###
