"""empty message

Revision ID: 9e339d4abc0b
Revises: d09303ad4a5f
Create Date: 2026-09-15 19:39:09.967011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e339d4abc0b'
down_revision = 'd09303ad4a5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # Шаг 2: Принудительно прописываем True всем существующим тестовым аккаунтам
    op.execute("UPDATE users SET confirmed = TRUE")

    # Шаг 3: Теперь, когда пустых ячеек не осталось, жестко включаем ограничение NOT NULL
    op.alter_column('users', 'confirmed', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
