"""empty message

Revision ID: a9c2e1325d97
Revises: 822a2358dd16
Create Date: 2025-11-18 21:50:58.053866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9c2e1325d97'
down_revision = '822a2358dd16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
