"""empty message

Revision ID: c29261c1ba23
Revises: 
Create Date: 2025-08-15 21:51:30.604289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c29261c1ba23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mail', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_mail'), ['mail'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_mail'))
        batch_op.drop_column('mail')

    # ### end Alembic commands ###
