"""empty message

Revision ID: d09303ad4a5f
Revises: 0b62a40bf721
Create Date: 2026-09-14 22:12:53.187888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09303ad4a5f'
down_revision = '0b62a40bf721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bar_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bar_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bar_id'], ['bars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('managers')
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_secret_hash', sa.String(length=128), nullable=True))
        batch_op.create_unique_constraint(None, ['qr_secret_hash'])
        batch_op.drop_constraint('bars_admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_constraint('drinks_bar_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bars', ['bar_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role_id')
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('drinks_bar_id_fkey', 'bars', ['bar_id'], ['id'])

    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('bars_admin_id_fkey', 'users', ['admin_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('qr_secret_hash')

    op.create_table('managers',
    sa.Column('manager_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], name='managers_manager_id_fkey'),
    sa.PrimaryKeyConstraint('manager_id', name='managers_pkey')
    )
    op.drop_table('bar_checkins')
    # ### end Alembic commands ###
