"""empty message

Revision ID: d9453ae300ef
Revises: 8bdadba6254d
Create Date: 2025-11-16 19:56:28.968934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9453ae300ef'
down_revision = '8bdadba6254d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_constraint('drinks_name_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.create_unique_constraint('drinks_name_key', ['name'])

    # ### end Alembic commands ###
