"""empty message

Revision ID: fab7c33d06b4
Revises: 3afb3e1c3df3
Create Date: 2025-10-14 21:27:14.030447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab7c33d06b4'
down_revision = '3afb3e1c3df3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bars', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
